### ISSUE TITLE
It didn't work

### ISSUE THREAD

**Issue by inancgumus** [technology-ebay-de/universal-react-router4#1]
Hi thx for the article on Medium. I tried the code but it gave me errors. Probably some versioning issue.

```bash
> npm i
> npm run build
> npm start
> universal-react-router4@1.0.0 start /Users/inanc/dev/universal-react-router4
> node dist/server.js
Demo app listening on port 3000
Warning: Failed context type: The context `router` is marked as required in `Link`, but its value is `undefined`.
 in Link (created by Unknown)
 in p (created by Unknown)
 in Unknown (created by Unknown)
 in aside (created by Unknown)
 in Unknown (created by Unknown)
 in div (created by Unknown)
 in Unknown
 in Router (created by StaticRouter)
 in StaticRouter
TypeError: Cannot read property ‘createHref’ of undefined
 at Link.render (/Users/inanc/dev/universal-react-router4/node_modules/react-router-dom/Link.js:72:35)
 at /Users/inanc/dev/universal-react-router4/node_modules/react-dom/lib/ReactCompositeComponent.js:796:21
 at measureLifeCyclePerf (/Users/inanc/dev/universal-react-router4/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
 at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Users/inanc/dev/universal-react-router4/node_modules/react-dom/lib/ReactCompositeComponent.js:795:25)
 at ReactCompositeComponentWrapper._renderValidatedComponent (/Users/inanc/dev/universal-react-router4/node_modules/react-dom/lib/ReactCompositeComponent.js:822:32)
 at ReactCompositeComponentWrapper.performInitialMount (/Users/inanc/dev/universal-react-router4/node_modules/react-dom/lib/ReactCompositeComponent.js:362:30)
 at ReactCompositeComponentWrapper.mountComponent (/Users/inanc/dev/universal-react-router4/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
 at Object.mountComponent (/Users/inanc/dev/universal-react-router4/node_modules/react-dom/lib/ReactReconciler.js:46:35)
 at ReactDOMComponent.mountChildren (/Users/inanc/dev/universal-react-router4/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
 at ReactDOMComponent._createContentMarkup (/Users/inanc/dev/universal-react-router4/node_modules/react-dom/lib/ReactDOMComponent.js:653:32)
TypeError: Cannot read property ‘createHref’ of undefined
 at Link.render (/Users/inanc/dev/universal-react-router4/node_modules/react-router-dom/Link.js:72:35)
 at /Users/inanc/dev/universal-react-router4/node_modules/react-dom/lib/ReactCompositeComponent.js:796:21
 at measureLifeCyclePerf (/Users/inanc/dev/universal-react-router4/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
 at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Users/inanc/dev/universal-react-router4/node_modules/react-dom/lib/ReactCompositeComponent.js:795:25)
 at ReactCompositeComponentWrapper._renderValidatedComponent (/Users/inanc/dev/universal-react-router4/node_modules/react-dom/lib/ReactCompositeComponent.js:822:32)
 at ReactCompositeComponentWrapper.performInitialMount (/Users/inanc/dev/universal-react-router4/node_modules/react-dom/lib/ReactCompositeComponent.js:362:30)
 at ReactCompositeComponentWrapper.mountComponent (/Users/inanc/dev/universal-react-router4/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
 at Object.mountComponent (/Users/inanc/dev/universal-react-router4/node_modules/react-dom/lib/ReactReconciler.js:46:35)
 at ReactDOMComponent.mountChildren (/Users/inanc/dev/universal-react-router4/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
 at ReactDOMComponent._createContentMarkup (/Users/inanc/dev/universal-react-router4/node_modules/react-dom/lib/ReactDOMComponent.js:653:32)
```

**Comment by jdobrowner** [comment]
It worked for me

**Comment by pahund** [comment]
Sorry for the late reply 😄 

I can't reproduce the problem, I've just installed the project on a clean system and it works just fine.
